#!/bin/bash

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

jq --help > /dev/null 2>&1
if [ $? -eq 127 ]
then
    echo "jq is not installed\nPlease install it from your distributions' package manager"
    exit 1
fi

echo -en "Generating qwote..."
echo
json=$(curl -s "https://api.quotable.io/random?maxLength=110")

if [ -z "$json" ]
then
    echo -en "Cannot connect to host."
    echo
else
    echo $json | jq '.content' > $HOME/.cache/qwote.txt
    echo $json | jq '.author' | cut -d '"' -f 2 > $HOME/.cache/author.txt
    echo -en "${BLUE}Successfully generated qwote!${NC}"
    echo
fi

echo "Your qwote now reads:"
echo
echo -en "${RED}\e[3m❤ $(cat $HOME/.cache/qwote.txt) ❤\e[0m${NC}"
echo -en "\n${BLUE}\e[3m- $(cat $HOME/.cache/author.txt)\e[0m${NC}"
echo
